//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Energetic_Simple_Asset.AssetWebApi {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Asset")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ColumnBasic", Namespace="http://schemas.datacontract.org/2004/07/Asset")]
    [System.SerializableAttribute()]
    public partial class ColumnBasic : Energetic_Simple_Asset.AssetWebApi.BasicLineColumn {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] categoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal[] dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] categories {
            get {
                return this.categoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.categoriesField, value) != true)) {
                    this.categoriesField = value;
                    this.RaisePropertyChanged("categories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal[] data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasicLineColumn", Namespace="http://schemas.datacontract.org/2004/07/Asset")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Energetic_Simple_Asset.AssetWebApi.ColumnBasic))]
    public partial class BasicLineColumn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChartSubtitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChartTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChartTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XAxisTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YAxisTitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChartSubtitle {
            get {
                return this.ChartSubtitleField;
            }
            set {
                if ((object.ReferenceEquals(this.ChartSubtitleField, value) != true)) {
                    this.ChartSubtitleField = value;
                    this.RaisePropertyChanged("ChartSubtitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChartTitle {
            get {
                return this.ChartTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.ChartTitleField, value) != true)) {
                    this.ChartTitleField = value;
                    this.RaisePropertyChanged("ChartTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChartType {
            get {
                return this.ChartTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ChartTypeField, value) != true)) {
                    this.ChartTypeField = value;
                    this.RaisePropertyChanged("ChartType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XAxisTitle {
            get {
                return this.XAxisTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.XAxisTitleField, value) != true)) {
                    this.XAxisTitleField = value;
                    this.RaisePropertyChanged("XAxisTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YAxisTitle {
            get {
                return this.YAxisTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.YAxisTitleField, value) != true)) {
                    this.YAxisTitleField = value;
                    this.RaisePropertyChanged("YAxisTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultModelType", Namespace="http://schemas.datacontract.org/2004/07/Asset")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Energetic_Simple_Asset.AssetWebApi.CompositeType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Energetic_Simple_Asset.AssetWebApi.ColumnBasic[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Energetic_Simple_Asset.AssetWebApi.ColumnBasic))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Energetic_Simple_Asset.AssetWebApi.BasicLineColumn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(decimal[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ArrayList))]
    public partial class ResultModelType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ASSET_DESCRIPTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ASSET_EPCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ASSET_FIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ASSET_LABELField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ASSET_TIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ASSET_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ArrayList DataObjectsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet DataSetResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] DataTextsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ROOM_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ROOM_DESCRIPTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ROOM_EPCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ROOM_TIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ASSET_DESCRIPTION {
            get {
                return this.ASSET_DESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.ASSET_DESCRIPTIONField, value) != true)) {
                    this.ASSET_DESCRIPTIONField = value;
                    this.RaisePropertyChanged("ASSET_DESCRIPTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ASSET_EPC {
            get {
                return this.ASSET_EPCField;
            }
            set {
                if ((object.ReferenceEquals(this.ASSET_EPCField, value) != true)) {
                    this.ASSET_EPCField = value;
                    this.RaisePropertyChanged("ASSET_EPC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ASSET_FID {
            get {
                return this.ASSET_FIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ASSET_FIDField, value) != true)) {
                    this.ASSET_FIDField = value;
                    this.RaisePropertyChanged("ASSET_FID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ASSET_LABEL {
            get {
                return this.ASSET_LABELField;
            }
            set {
                if ((object.ReferenceEquals(this.ASSET_LABELField, value) != true)) {
                    this.ASSET_LABELField = value;
                    this.RaisePropertyChanged("ASSET_LABEL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ASSET_TID {
            get {
                return this.ASSET_TIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ASSET_TIDField, value) != true)) {
                    this.ASSET_TIDField = value;
                    this.RaisePropertyChanged("ASSET_TID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ASSET_TYPE {
            get {
                return this.ASSET_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.ASSET_TYPEField, value) != true)) {
                    this.ASSET_TYPEField = value;
                    this.RaisePropertyChanged("ASSET_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ArrayList DataObjects {
            get {
                return this.DataObjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.DataObjectsField, value) != true)) {
                    this.DataObjectsField = value;
                    this.RaisePropertyChanged("DataObjects");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet DataSetResult {
            get {
                return this.DataSetResultField;
            }
            set {
                if ((object.ReferenceEquals(this.DataSetResultField, value) != true)) {
                    this.DataSetResultField = value;
                    this.RaisePropertyChanged("DataSetResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] DataTexts {
            get {
                return this.DataTextsField;
            }
            set {
                if ((object.ReferenceEquals(this.DataTextsField, value) != true)) {
                    this.DataTextsField = value;
                    this.RaisePropertyChanged("DataTexts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Flag {
            get {
                return this.FlagField;
            }
            set {
                if ((this.FlagField.Equals(value) != true)) {
                    this.FlagField = value;
                    this.RaisePropertyChanged("Flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ROOM_CODE {
            get {
                return this.ROOM_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.ROOM_CODEField, value) != true)) {
                    this.ROOM_CODEField = value;
                    this.RaisePropertyChanged("ROOM_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ROOM_DESCRIPTION {
            get {
                return this.ROOM_DESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.ROOM_DESCRIPTIONField, value) != true)) {
                    this.ROOM_DESCRIPTIONField = value;
                    this.RaisePropertyChanged("ROOM_DESCRIPTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ROOM_EPC {
            get {
                return this.ROOM_EPCField;
            }
            set {
                if ((object.ReferenceEquals(this.ROOM_EPCField, value) != true)) {
                    this.ROOM_EPCField = value;
                    this.RaisePropertyChanged("ROOM_EPC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ROOM_TID {
            get {
                return this.ROOM_TIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ROOM_TIDField, value) != true)) {
                    this.ROOM_TIDField = value;
                    this.RaisePropertyChanged("ROOM_TID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowCount {
            get {
                return this.RowCountField;
            }
            set {
                if ((this.RowCountField.Equals(value) != true)) {
                    this.RowCountField = value;
                    this.RaisePropertyChanged("RowCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AssetWebApi.IAssetService")]
    public interface IAssetService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/GetData", ReplyAction="http://tempuri.org/IAssetService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/GetData", ReplyAction="http://tempuri.org/IAssetService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAssetService/GetDataUsingDataContractResponse")]
        Energetic_Simple_Asset.AssetWebApi.CompositeType GetDataUsingDataContract(Energetic_Simple_Asset.AssetWebApi.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAssetService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.CompositeType> GetDataUsingDataContractAsync(Energetic_Simple_Asset.AssetWebApi.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/MorningCheck", ReplyAction="http://tempuri.org/IAssetService/MorningCheckResponse")]
        string MorningCheck();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/MorningCheck", ReplyAction="http://tempuri.org/IAssetService/MorningCheckResponse")]
        System.Threading.Tasks.Task<string> MorningCheckAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/TestList", ReplyAction="http://tempuri.org/IAssetService/TestListResponse")]
        Energetic_Simple_Asset.AssetWebApi.ColumnBasic[] TestList(string arg1, string arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/TestList", ReplyAction="http://tempuri.org/IAssetService/TestListResponse")]
        System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ColumnBasic[]> TestListAsync(string arg1, string arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/SearchByTid", ReplyAction="http://tempuri.org/IAssetService/SearchByTidResponse")]
        Energetic_Simple_Asset.AssetWebApi.ResultModelType SearchByTid(string tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/SearchByTid", ReplyAction="http://tempuri.org/IAssetService/SearchByTidResponse")]
        System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> SearchByTidAsync(string tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/SearchByFid", ReplyAction="http://tempuri.org/IAssetService/SearchByFidResponse")]
        Energetic_Simple_Asset.AssetWebApi.ResultModelType SearchByFid(string fid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/SearchByFid", ReplyAction="http://tempuri.org/IAssetService/SearchByFidResponse")]
        System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> SearchByFidAsync(string fid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/Save", ReplyAction="http://tempuri.org/IAssetService/SaveResponse")]
        Energetic_Simple_Asset.AssetWebApi.ResultModelType Save(string RoomCode, string Epc, string Tid, string Fid, string AssetLabel, string AssetType, string AssetDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/Save", ReplyAction="http://tempuri.org/IAssetService/SaveResponse")]
        System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> SaveAsync(string RoomCode, string Epc, string Tid, string Fid, string AssetLabel, string AssetType, string AssetDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/SearchByRoomCode", ReplyAction="http://tempuri.org/IAssetService/SearchByRoomCodeResponse")]
        Energetic_Simple_Asset.AssetWebApi.ResultModelType SearchByRoomCode(string RoomCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/SearchByRoomCode", ReplyAction="http://tempuri.org/IAssetService/SearchByRoomCodeResponse")]
        System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> SearchByRoomCodeAsync(string RoomCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/SearchByRoomTID", ReplyAction="http://tempuri.org/IAssetService/SearchByRoomTIDResponse")]
        Energetic_Simple_Asset.AssetWebApi.ResultModelType SearchByRoomTID(string rtid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/SearchByRoomTID", ReplyAction="http://tempuri.org/IAssetService/SearchByRoomTIDResponse")]
        System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> SearchByRoomTIDAsync(string rtid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/RoomSave", ReplyAction="http://tempuri.org/IAssetService/RoomSaveResponse")]
        Energetic_Simple_Asset.AssetWebApi.ResultModelType RoomSave(string Epc, string Tid, string RoomCode, string RoomDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/RoomSave", ReplyAction="http://tempuri.org/IAssetService/RoomSaveResponse")]
        System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> RoomSaveAsync(string Epc, string Tid, string RoomCode, string RoomDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/RoomAssetSearchByAssetTID", ReplyAction="http://tempuri.org/IAssetService/RoomAssetSearchByAssetTIDResponse")]
        Energetic_Simple_Asset.AssetWebApi.ResultModelType RoomAssetSearchByAssetTID(string AssetTID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/RoomAssetSearchByAssetTID", ReplyAction="http://tempuri.org/IAssetService/RoomAssetSearchByAssetTIDResponse")]
        System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> RoomAssetSearchByAssetTIDAsync(string AssetTID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/RoomAssetSearchByAssetFID", ReplyAction="http://tempuri.org/IAssetService/RoomAssetSearchByAssetFIDResponse")]
        Energetic_Simple_Asset.AssetWebApi.ResultModelType RoomAssetSearchByAssetFID(string AssetFID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/RoomAssetSearchByAssetFID", ReplyAction="http://tempuri.org/IAssetService/RoomAssetSearchByAssetFIDResponse")]
        System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> RoomAssetSearchByAssetFIDAsync(string AssetFID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/RoomAsset_AssetSave", ReplyAction="http://tempuri.org/IAssetService/RoomAsset_AssetSaveResponse")]
        Energetic_Simple_Asset.AssetWebApi.ResultModelType RoomAsset_AssetSave(string room_tid, string room_code, string room_description, string asset_tid, string asset_fid, string asset_label, string asset_description, string epc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/RoomAsset_AssetSave", ReplyAction="http://tempuri.org/IAssetService/RoomAsset_AssetSaveResponse")]
        System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> RoomAsset_AssetSaveAsync(string room_tid, string room_code, string room_description, string asset_tid, string asset_fid, string asset_label, string asset_description, string epc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/RoomAssetSearchByRoomTID", ReplyAction="http://tempuri.org/IAssetService/RoomAssetSearchByRoomTIDResponse")]
        Energetic_Simple_Asset.AssetWebApi.ResultModelType RoomAssetSearchByRoomTID(string RoomTID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/RoomAssetSearchByRoomTID", ReplyAction="http://tempuri.org/IAssetService/RoomAssetSearchByRoomTIDResponse")]
        System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> RoomAssetSearchByRoomTIDAsync(string RoomTID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/RoomAssetSearchByRoomCode", ReplyAction="http://tempuri.org/IAssetService/RoomAssetSearchByRoomCodeResponse")]
        Energetic_Simple_Asset.AssetWebApi.ResultModelType RoomAssetSearchByRoomCode(string ROOM_CODE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/RoomAssetSearchByRoomCode", ReplyAction="http://tempuri.org/IAssetService/RoomAssetSearchByRoomCodeResponse")]
        System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> RoomAssetSearchByRoomCodeAsync(string ROOM_CODE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/RoomAsset_RoomSave", ReplyAction="http://tempuri.org/IAssetService/RoomAsset_RoomSaveResponse")]
        Energetic_Simple_Asset.AssetWebApi.ResultModelType RoomAsset_RoomSave(string room_tid, string room_code, string room_description, string asset_tid, string asset_fid, string asset_label, string asset_description, string epc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/RoomAsset_RoomSave", ReplyAction="http://tempuri.org/IAssetService/RoomAsset_RoomSaveResponse")]
        System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> RoomAsset_RoomSaveAsync(string room_tid, string room_code, string room_description, string asset_tid, string asset_fid, string asset_label, string asset_description, string epc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/RoomAssetSelectAll", ReplyAction="http://tempuri.org/IAssetService/RoomAssetSelectAllResponse")]
        Energetic_Simple_Asset.AssetWebApi.ResultModelType RoomAssetSelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/RoomAssetSelectAll", ReplyAction="http://tempuri.org/IAssetService/RoomAssetSelectAllResponse")]
        System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> RoomAssetSelectAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAssetServiceChannel : Energetic_Simple_Asset.AssetWebApi.IAssetService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AssetServiceClient : System.ServiceModel.ClientBase<Energetic_Simple_Asset.AssetWebApi.IAssetService>, Energetic_Simple_Asset.AssetWebApi.IAssetService {
        
        public AssetServiceClient() {
        }
        
        public AssetServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AssetServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssetServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssetServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Energetic_Simple_Asset.AssetWebApi.CompositeType GetDataUsingDataContract(Energetic_Simple_Asset.AssetWebApi.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.CompositeType> GetDataUsingDataContractAsync(Energetic_Simple_Asset.AssetWebApi.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string MorningCheck() {
            return base.Channel.MorningCheck();
        }
        
        public System.Threading.Tasks.Task<string> MorningCheckAsync() {
            return base.Channel.MorningCheckAsync();
        }
        
        public Energetic_Simple_Asset.AssetWebApi.ColumnBasic[] TestList(string arg1, string arg2) {
            return base.Channel.TestList(arg1, arg2);
        }
        
        public System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ColumnBasic[]> TestListAsync(string arg1, string arg2) {
            return base.Channel.TestListAsync(arg1, arg2);
        }
        
        public Energetic_Simple_Asset.AssetWebApi.ResultModelType SearchByTid(string tid) {
            return base.Channel.SearchByTid(tid);
        }
        
        public System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> SearchByTidAsync(string tid) {
            return base.Channel.SearchByTidAsync(tid);
        }
        
        public Energetic_Simple_Asset.AssetWebApi.ResultModelType SearchByFid(string fid) {
            return base.Channel.SearchByFid(fid);
        }
        
        public System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> SearchByFidAsync(string fid) {
            return base.Channel.SearchByFidAsync(fid);
        }
        
        public Energetic_Simple_Asset.AssetWebApi.ResultModelType Save(string RoomCode, string Epc, string Tid, string Fid, string AssetLabel, string AssetType, string AssetDescription) {
            return base.Channel.Save(RoomCode, Epc, Tid, Fid, AssetLabel, AssetType, AssetDescription);
        }
        
        public System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> SaveAsync(string RoomCode, string Epc, string Tid, string Fid, string AssetLabel, string AssetType, string AssetDescription) {
            return base.Channel.SaveAsync(RoomCode, Epc, Tid, Fid, AssetLabel, AssetType, AssetDescription);
        }
        
        public Energetic_Simple_Asset.AssetWebApi.ResultModelType SearchByRoomCode(string RoomCode) {
            return base.Channel.SearchByRoomCode(RoomCode);
        }
        
        public System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> SearchByRoomCodeAsync(string RoomCode) {
            return base.Channel.SearchByRoomCodeAsync(RoomCode);
        }
        
        public Energetic_Simple_Asset.AssetWebApi.ResultModelType SearchByRoomTID(string rtid) {
            return base.Channel.SearchByRoomTID(rtid);
        }
        
        public System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> SearchByRoomTIDAsync(string rtid) {
            return base.Channel.SearchByRoomTIDAsync(rtid);
        }
        
        public Energetic_Simple_Asset.AssetWebApi.ResultModelType RoomSave(string Epc, string Tid, string RoomCode, string RoomDescription) {
            return base.Channel.RoomSave(Epc, Tid, RoomCode, RoomDescription);
        }
        
        public System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> RoomSaveAsync(string Epc, string Tid, string RoomCode, string RoomDescription) {
            return base.Channel.RoomSaveAsync(Epc, Tid, RoomCode, RoomDescription);
        }
        
        public Energetic_Simple_Asset.AssetWebApi.ResultModelType RoomAssetSearchByAssetTID(string AssetTID) {
            return base.Channel.RoomAssetSearchByAssetTID(AssetTID);
        }
        
        public System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> RoomAssetSearchByAssetTIDAsync(string AssetTID) {
            return base.Channel.RoomAssetSearchByAssetTIDAsync(AssetTID);
        }
        
        public Energetic_Simple_Asset.AssetWebApi.ResultModelType RoomAssetSearchByAssetFID(string AssetFID) {
            return base.Channel.RoomAssetSearchByAssetFID(AssetFID);
        }
        
        public System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> RoomAssetSearchByAssetFIDAsync(string AssetFID) {
            return base.Channel.RoomAssetSearchByAssetFIDAsync(AssetFID);
        }
        
        public Energetic_Simple_Asset.AssetWebApi.ResultModelType RoomAsset_AssetSave(string room_tid, string room_code, string room_description, string asset_tid, string asset_fid, string asset_label, string asset_description, string epc) {
            return base.Channel.RoomAsset_AssetSave(room_tid, room_code, room_description, asset_tid, asset_fid, asset_label, asset_description, epc);
        }
        
        public System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> RoomAsset_AssetSaveAsync(string room_tid, string room_code, string room_description, string asset_tid, string asset_fid, string asset_label, string asset_description, string epc) {
            return base.Channel.RoomAsset_AssetSaveAsync(room_tid, room_code, room_description, asset_tid, asset_fid, asset_label, asset_description, epc);
        }
        
        public Energetic_Simple_Asset.AssetWebApi.ResultModelType RoomAssetSearchByRoomTID(string RoomTID) {
            return base.Channel.RoomAssetSearchByRoomTID(RoomTID);
        }
        
        public System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> RoomAssetSearchByRoomTIDAsync(string RoomTID) {
            return base.Channel.RoomAssetSearchByRoomTIDAsync(RoomTID);
        }
        
        public Energetic_Simple_Asset.AssetWebApi.ResultModelType RoomAssetSearchByRoomCode(string ROOM_CODE) {
            return base.Channel.RoomAssetSearchByRoomCode(ROOM_CODE);
        }
        
        public System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> RoomAssetSearchByRoomCodeAsync(string ROOM_CODE) {
            return base.Channel.RoomAssetSearchByRoomCodeAsync(ROOM_CODE);
        }
        
        public Energetic_Simple_Asset.AssetWebApi.ResultModelType RoomAsset_RoomSave(string room_tid, string room_code, string room_description, string asset_tid, string asset_fid, string asset_label, string asset_description, string epc) {
            return base.Channel.RoomAsset_RoomSave(room_tid, room_code, room_description, asset_tid, asset_fid, asset_label, asset_description, epc);
        }
        
        public System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> RoomAsset_RoomSaveAsync(string room_tid, string room_code, string room_description, string asset_tid, string asset_fid, string asset_label, string asset_description, string epc) {
            return base.Channel.RoomAsset_RoomSaveAsync(room_tid, room_code, room_description, asset_tid, asset_fid, asset_label, asset_description, epc);
        }
        
        public Energetic_Simple_Asset.AssetWebApi.ResultModelType RoomAssetSelectAll() {
            return base.Channel.RoomAssetSelectAll();
        }
        
        public System.Threading.Tasks.Task<Energetic_Simple_Asset.AssetWebApi.ResultModelType> RoomAssetSelectAllAsync() {
            return base.Channel.RoomAssetSelectAllAsync();
        }
    }
}
